version: '3'
services:
  nestjs:
    image: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '5001:5000' # expose-to-the-world : only-in-the-docker
    container_name: bridge
    volumes:
      - ./bridge:/usr/src/app/bridge
    networks:
      - server

volumes:
  pgdata:
  pgadmin-data:
networks:
  server: